### ISSUE TITLE
how to integrate jest with pactum coverage

### ISSUE THREAD

**Issue by karishma1911** [leelaprasadv/pactum-swagger-coverage#5]
I was trying to perform the code coverage on the Api specification, but giving all the apis  even if run for  one api .
![Screenshot from 2022-01-03 18-13-01](https://user-images.githubusercontent.com/95741784/147931832-94772598-6605-4162-85ba-6f4be98083e3.png)

**Comment by ASaiAnudeep** [comment]
@karishma1911 Thanks for reporting. @leelaprasadv will investigate this further.

**Comment by leelaprasadv** [comment]
Similar to Issue: https://github.com/pactumjs/pactum-swagger-coverage/issues/6

Will be fixed with PR https://github.com/pactumjs/pactum-swagger-coverage/pull/7
