### ISSUE TITLE
complex endpoints are falsely reported as covered

### ISSUE THREAD

**Issue by pf-lkobbe** [leelaprasadv/pactum-swagger-coverage#6]
I noticed that the regExMatchOfPath function isn't working as expected. Say you have the following endpoints:
```
/foo
/foo/{foo-id}
/foo/{foo-id}/bar
/foo/{foo-id}/bar/{bar-id}
```

If you only test against /foo and /foo/{foo-id}, the other endpoints will nevertheless be marked as covered as well.

I believe this function in src/lib/core.js should be corrected as follows:
```
 function regExMatchOfPath(apiPath, rPath) {
-  if (apiPath.includes("{")) {
-    const idx = apiPath.indexOf("{");
-    apiPath = apiPath.substring(0, idx);
-  }
-  const regex = RegExp(apiPath);
+  const regex = RegExp(apiPath.replace(/{[^\/]+}/g,'.*'));
   return regex.test(rPath);
 }
```

Explanation: The apiPath.replace function changes all occurences of path parameters into simple `.*` wildcards, so the endpoints to test against become:
```
/foo
/foo/.*
/foo/.*/bar
/foo/.*/bar/.*
```

**Comment by ASaiAnudeep** [comment]
@pf-lkobbe Thanks for reporting the issue. Do you want raise a pr with the fix?

**Comment by leelaprasadv** [comment]
@pf-lkobbe Thanks for suggesting a fix.
With your logic, if there is an api `/foo/{foo-id}` it would translate to regex `/foo/.*`. which would match with all the below and will be pulled into covered list like earlier.
```
/foo/{foo-id}
/foo/{foo-id}/bar
/foo/{foo-id}/bar/{bar-id}
```
Raised a PR fixing the issue https://github.com/pactumjs/pactum-swagger-coverage/pull/7.
